hist(wage, freq = FALSE)
hist(log(wage), freq = FALSE)
lines(density(log(wage)))
summary(occupation)
summary(ethnicity)
tab <- table(occupation)
prop.table(tab)
barplot(tab) # == plot(occupation)
pie(tab)
