data("CPS1988", package = "AER")
head(CPS1988)
#a)
attach(CPS1988)
plot(log(wage) ~ experience)
plot(log(wage) ~ education)
#b)
range(education)
feduc <- factor(education, levels = 0:18)
plot(log(wage) ~ feduc)

range(experience)
fexpr <- factor(experience, levels = -4:63)
plot(log(wage) ~ fexpr)
#c)
plot(log(wage) ~ ethnicity)
plot(log(wage) ~ smsa)
plot(log(wage) ~ region)
plot(log(wage) ~ parttime)
